language: scala
sudo: false
jdk:
- oraclejdk8
dist: trusty
env:
  global:
  - TRAVIS_SBT_VERSION="1.2.8"
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/
before_install:
- nvm install 10 &&
  nvm use 10
- node --version
script:
- sbt clean coverage test coverageReport &&
  sbt coverageAggregate &&
  sbt coveralls
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
