name: CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache sbt
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt', 'project/**/*.scala') }}

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.nvm
          ~/work/codegalaxy-app/codegalaxy-app/app/node_modules
          ~/work/codegalaxy-app/codegalaxy-app/app/package-lock.json
          ~/work/codegalaxy-app/codegalaxy-app/app/target/scala-2.13/scalajs-bundler/main/node_modules
          ~/work/codegalaxy-app/codegalaxy-app/app/target/scala-2.13/scalajs-bundler/main/package-lock.json
          ~/work/codegalaxy-app/codegalaxy-app/app/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/codegalaxy-app/codegalaxy-app/app/target/scala-2.13/scalajs-bundler/test/package-lock.json
          ~/work/codegalaxy-app/codegalaxy-app/dao/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/codegalaxy-app/codegalaxy-app/dao/target/scala-2.13/scalajs-bundler/test/package-lock.json
        key: ${{ runner.os }}-node_modules-cache-v2-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-cache-v2-

    - name: Run tests
      run: sbt -mem 2048 coverage test && sbt coverageAggregate coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Extract Tag Name
      run: echo "TAG_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      if: ${{ startsWith(github.ref, 'refs/tags') }}

    - name: Publish SNAPSHOT
      run:
        sbt clean &&
        sbt -mem 2048 "project codegalaxy-app" fullOptJS &&
        cd app &&
        npm install &&
        npm install expo-cli --save-dev &&
        ./node_modules/expo-cli/bin/expo.js login -u $EXPO_USERNAME -p $EXPO_PASSWORD &&
        NODE_OPTIONS=--max_old_space_size=4096 EXPO_ENV=production ./node_modules/expo-cli/bin/expo.js publish --non-interactive
      if: ${{ !github.event.pull_request && env.TAG_NAME == '' }}
      env:
        EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
        EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}

    - name: Publish RELEASE
      run:
        VERSION="$(echo "$TAG_NAME" | cut -d'v' -f 2)" &&
        echo "Publish a release version=$VERSION for tag $TAG_NAME"
      if: ${{ env.TAG_NAME != '' }}
